### ISSUE TITLE
Excellent OTP-solution with some minor issues.

### ISSUE THREAD

**Issue by maskinmedia** [froger-me/otp-authenticator#1]
First of all huge thank you for developing the OTP-authenticator! It's exactly what I have been looking for for quite some time. Good looking both in front- and back end, with well designed functionality. In short: excellent job!

We are running it on our website but, there are a few issues that we would like to get up to speed with. To make it easier am creating one issue for each issue, starting with:

**Activation on a multisite**
Network activation of OTP-authenticator does not work at all in our set up, a multisite where mentabee.com (english) is the root site, with mentabee.se (swedish) and mentabee.com/it (italian) as sub domains. 

Clicking "Network activate" does not give any result at all.

**Comment by froger-me** [comment]
Hi @maskinmedia !
Thank you for the praise!
I do not intend to support Multisite in the foreseeable future though...
