### ISSUE TITLE
Error code: OTP Identifier field is required.

### ISSUE THREAD

**Issue by maskinmedia** [froger-me/otp-authenticator#2]
Administrator that tries edit user info on a multisite, on any of the sites from the backend, in any common user field, the response is this error code: OTP Identifier field is required.

Further clues:
1) If, in the user settings, a users "Account Validation Status" is Not validated it can be set to Validated by pressing the Toggle Validation Button. This does not produce the above mentioned error message.

2) If, in the user settings, the account has been validated by admin as in 1 above, and a user try to login, a code will be sent to the user by email, and the user may login. i.e. it works as expected.

3) If the account is validated by admin as in 1, the user has not yet logged in and the admin revoke the validation, an error appear for the admin saying User ID is not valid. IF the user has logged in however, this error does not occur.

Suspicion: The cause of the above problems may be because the OTP identifier is not registered correctly for multisites, but it's a guess.

**Comment by froger-me** [comment]
Hi @maskinmedia ! I'm gonna close this issue, for the same reasons as [this one](https://github.com/froger-me/otp-authenticator/issues/1).
Please don't hesitate to open a new one if similar problems happen on a classic WP install.
Also, pull requests are welcome :-).
